### ISSUE TITLE
How are transactions getting signed ?

### ISSUE THREAD

**Issue by jalchr** [Normalizex/1inch-api-v4#1]
Hello,
I'm new to swapping and had a chance to check your great library.

As per the following:
` https://docs.1inch.io/docs/aggregation-protocol/guide/quick-start `

They use a url for sending signed transactions 
`const broadcastApiUrl = 'https://tx-gateway.1inch.io/v1.1/' + chainId + '/broadcast';`

My question is: Is your library handling this ?
If yes, how ?
If no, what is your alternative ?

Thank you

**Comment by Normalizex** [comment]
> Hello, I'm new to swapping and had a chance to check your great library.
> 
> As per the following: `https://docs.1inch.io/docs/aggregation-protocol/guide/quick-start`
> 
> They use a url for sending signed transactions `const broadcastApiUrl = 'https://tx-gateway.1inch.io/v1.1/' + chainId + '/broadcast';`
> 
> My question is: Is your library handling this ? If yes, how ? If no, what is your alternative ?
> 
> Thank you

I sign and send the transaction with web3.js

Example:
```js
import Web3 from "web3";
import OneInchApi, { InchV4Chains } from "@normalizex/1inch-api-v4";

const web3RpcUrl = 'https://bsc-dataseed.binance.org';
const privateKey = '0x...xxx'; // Set private key of your wallet. Be careful! Don't share this key to anyone!
const walletAddress = web3.eth.accounts.privateKeyToAccount(privateKey).address;

const gasPrice = 5;
const swapParams = {
    fromTokenAddress: '0x111111111117dc0aa78b770fa6a738034120c302', // 1INCH
    toTokenAddress: '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3', // DAI
    amount: '100000000000000000',
    fromAddress: walletAddress,
    slippage: 1,
    disableEstimate: false,
    allowPartialFill: false,
};
const web3 = new Web3(web3RpcUrl);
const inch = new OneInchApi(InchV4Chains.BinanceSmartChain);

const quote = await inch.swap(swapParams);

const nonce = await web3.eth.getTransactionCount(walletAddress);

const transaction = {
    from: walletAddress,
    gasPrice: web3.utils.toHex(web3.utils.toWei(gasPrice, "Gwei")),
    gasLimit: web3.utils.toHex(quote.tx.gas),
    to: web3.utils.toChecksumAddress(quote.tx.to),
    value: web3.utils.toHex(quote.tx.value),
    data: quote.tx.data,
    nonce: web3.utils.toHex(nonce),
};

const { rawTransaction } = await web3.eth.accounts.signTransaction(transaction, privateKey);
await web3.eth.sendSignedTransaction(rawTransaction, (err, hash) => {
    // do something...
});
```

**Comment by Normalizex** [comment]
@jalchr Of course, I was late with the answer, but I think this option will suit?

**Comment by Normalizex** [comment]
@jalchr Of course, I was late with the answer, but I think this option will suit?
